---
abstract: 'OOP for the pinboard.in API'
author:
  - 'Aaron Straup Cope <ascope@cpan.org>'
build_requires:
  Test::Simple: 0.47
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Pinboard
provides:
  Net::Pinboard:
    file: lib/Net/Pinboard.pm
    version: 2.0
  Net::Pinboard::Bundle:
    file: lib/Net/Pinboard/Bundle.pm
    version: 2.0
  Net::Pinboard::Config:
    file: lib/Net/Pinboard/Config.pm
    version: 2.0
  Net::Pinboard::Constants:
    file: lib/Net/Pinboard/Constants.pm
    version: 2.0
  Net::Pinboard::Constants::Config:
    file: lib/Net/Pinboard/Constants/Config.pm
    version: 2.0
  Net::Pinboard::Constants::Pause:
    file: lib/Net/Pinboard/Constants/Pause.pm
    version: 1.13
  Net::Pinboard::Constants::Response:
    file: lib/Net/Pinboard/Constants/Response.pm
    version: 2.0
  Net::Pinboard::Constants::Uri:
    file: lib/Net/Pinboard/Constants/Uri.pm
    version: 1.13
  Net::Pinboard::Date:
    file: lib/Net/Pinboard/Date.pm
    version: 2.0
  Net::Pinboard::Iterator:
    file: lib/Net/Pinboard/Iterator.pm
    version: 2.0
  Net::Pinboard::Object:
    file: lib/Net/Pinboard/Object.pm
    version: 2.0
  Net::Pinboard::Post:
    file: lib/Net/Pinboard/Post.pm
    version: 2.0
  Net::Pinboard::Subscription:
    file: lib/Net/Pinboard/Subscription.pm
    version: 2.0
  Net::Pinboard::Tag:
    file: lib/Net/Pinboard/Tag.pm
    version: 2.0
  Net::Pinboard::User:
    file: lib/Net/Pinboard/User.pm
    version: 2.0
requires:
  Config::Simple: 2
  Crypt::SSLeay: 0
  Date::Parse: 2.27
  File::Spec: 0.8
  FileHandle: 2
  HTTP::Request: 0
  IO::AtomicFile: 2.1
  LWP::UserAgent: 0
  Log::Dispatch: 2
  Time::HiRes: 1.65
  URI: 0
  XML::Simple: 2
  YAML: 0.35
resources:
  license: http://dev.perl.org/licenses/
version: 2.0
